services:
  app:
    build:  # Diz ao Docker buildar a imagem com as costumizações feitas no Dockerfile, localizado na Raiz do projeto
      context: .
      dockerfile: Dockerfile
    container_name: php  # Nome dado para o Container
    ports: # Definindo em qual porta este serviço vai rodar
      - "8080:80" # A sintaxe é porta_local : porta_container, a porta 8080 é acessada pelo Navegador
      # e a porta 80 é a do servidor Web(HTTP) rodando dentro do container.

    environment:  # Define as variaveis de Ambiente para poder fazer a conexão com o Container do MySQL
      DB_HOST: db
      DB_USER: superUsuario
      DB_PASSWORD: simplicidade1
      DB_NAME: crudFernando

    volumes: # Volumes serve para espelhar arquivos locais para dentro do Container
      - ./src:/var/www/html # Neste caso está dizendo para montar toda a pasta '/src' dentro de '/var/www/html'

    depends_on: # Define que este serviço depende do serviço 'db'
      - db
    networks: # Rede local onde este serviço está rodando
      - bridge_communication
    
  db:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped  # Define que o serviço vai ser restartado automaticamente caso aconteça algum erro de montagem.
    environment:  # Define as variaveis de Ambiente para acessar o Banco
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crudFernando
      MYSQL_USER: superUsuario
      MYSQL_PASSWORD: simplicidade1

    ports:
      - "3306:3306"

    volumes:  # Caminho de Pastas onde vai rodar o Banco 
      - mysql_data:/var/lib/mysql  # Isto funciona para armazenar os dados permanentemente
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql # Está linha serve para verificar se o banco inicializado tem a Tabela 'produtos'
      # se não tiver ele espelha e executa os comandos do 'db.sql' que está na minha pasta Raiz.

    networks: # Rede local onde este serviço está rodando
      - bridge_communication

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment: # Define as variaveis de Ambiente para poder fazer a conexão com o Container do MySQL
      PMA_HOST: db # Define que o phpMyAdmin deve se conectar ao container cujo serviço se chama 'db'
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - bridge_communication
  
volumes: # Declaração do Volume gerenciado pelo serviço db(MySQL) do Docker permitindo o armazenamento de dados, mesmo após o ciclo de vida dos containers.
  mysql_data:

networks: # Declaração da rede personalizada com o intuito de isolar e fazer a conexão dos serviços dentro dela.
  bridge_communication: # Nome da Rede criada
    driver: bridge # Cria uma rede virtual privada para que os containers se comuniquem via nome atribuido com segurança
      